import * as clobV2 from "./clob-v2/structs";
import * as clob from "./clob/structs";
import * as critbit from "./critbit/structs";
import * as custodianV2 from "./custodian-v2/structs";
import * as custodian from "./custodian/structs";
import * as orderQuery from "./order-query/structs";
import {StructClassLoader} from "../_framework/loader";

export function registerClasses(loader: StructClassLoader) { loader.register(custodian.Account);
loader.register(custodian.AccountCap);
loader.register(custodian.Custodian);
loader.register(critbit.CritbitTree);
loader.register(critbit.InternalNode);
loader.register(critbit.Leaf);
loader.register(clob.Order);
loader.register(clob.OrderCanceled);
loader.register(clob.OrderFilled);
loader.register(clob.OrderFilledV2);
loader.register(clob.OrderPlaced);
loader.register(clob.OrderPlacedV2);
loader.register(clob.Pool);
loader.register(clob.PoolCreated);
loader.register(clob.TickLevel);
loader.register(custodianV2.Account);
loader.register(custodianV2.AccountCap);
loader.register(custodianV2.Custodian);
loader.register(clobV2.Order);
loader.register(clobV2.OrderCanceled);
loader.register(clobV2.OrderFilled);
loader.register(clobV2.OrderPlaced);
loader.register(clobV2.Pool);
loader.register(clobV2.PoolCreated);
loader.register(clobV2.TickLevel);
loader.register(clobV2.AllOrdersCanceled);
loader.register(clobV2.AllOrdersCanceledComponent);
loader.register(clobV2.DepositAsset);
loader.register(clobV2.MatchedOrderMetadata);
loader.register(clobV2.PoolOwnerCap);
loader.register(clobV2.WithdrawAsset);
loader.register(orderQuery.OrderPage);
 }
